
on:
  issues:
    types:
      [
        opened,
        closed,
        edited,
        demilestoned,
        milestoned,
        reopened,
        assigned,
        unassigned,
        labeled,
        unlabeled,
      ]
  pull_request:
    types:
      [
        opened,
        closed,
        edited,
        demilestoned,
        milestoned,
        reopened,
        assigned,
        unassigned,
        labeled,
        unlabeled,
      ]

jobs:
  milestones_data_job:
    runs-on: ubuntu-latest
    name: Gantt plantuml generator
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Gantt file
        id: milestone-data
        uses: pchainho/gantt-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit Gantt plantuml file
        uses: EndBug/add-and-commit@v4.4.0
        with:
          message: "autogen(docs): update gantt document"
          author_name: pch
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_PRIVILEGED }}
      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@master
        with:
          message: "Render Gantt graph"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
          
