name: gantt chart generator
on: issues

jobs:
  milestones-plantuml:
    runs-on: ubuntu-latest
    name: Gantt plantuml generator
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Create Gantt file
        id: milestone-data
        uses: pchainho/gantt-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit Gantt plantuml file
        uses: EndBug/add-and-commit@v4.4.0
        with:
          message: "autogen(docs): update gantt document"
          author_name: pch
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_PRIVILEGED }}
  gantt-graph:
    needs: [milestones-plantuml]
    runs-on: ubuntu-latest
    name: generate gantt graph
    steps:
      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
