name: gantt chart generator
on: [issues,milestone]
permissions:
  contents: write
  actions: write
  repository-projects: write
  issues: write

jobs:
  milestones-plantuml:
    runs-on: ubuntu-latest
    name: Gantt plantuml generator
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Create Gantt file
        id: milestone-data
        uses: pchainho/gantt-action@graphQL
        env:
          GRAPHQL_TOKEN: ${{ secrets.GRAPHQL }}
      - name: Commit Gantt plantuml file
        uses: EndBug/add-and-commit@v4.4.0
        with:
          message: "autogen(docs): update gantt document"
          author_name: pch
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_PRIVILEGED }}
