
on: [push]

jobs:
  milestones_data_job:
    runs-on: ubuntu-latest
    name: Get milestones data
    steps:
      - name: Get Miletones step
        id: milestone-data
        uses: pchainho/gantt-action@v0.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository: ${{ github.repository }}
          
      - name: Debug milestone value
        run: echo "Title ${{ steps.milestone-data.outputs }}"
