
on: [push]

jobs:
  milestones_data_job:
    runs-on: ubuntu-latest
    name: Get milestones data
    steps:
      - name: Get Miletones step
        id: milestone-data
        uses: pchainho/gantt-action@v0.4-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Debug milestone value
        run: echo "Title ${{ steps.milestone-data.outputs }}"
